mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

message:
  base_file_path: "/message/message-base.yml"
  file_path_list:
    - "/message/000-common-response-message.yml"
    - "/message/001-sign-response-message.yml"
    - "/message/002-user-component-response-message.yml"

interceptor:
  contains_white_list:
    - "swagger-ui"
    - "api-docs"
    - "h2-console"
  starts_with_white_list:
    - "/api/sign-in"
    - "/api/sign-up"
    - "/api/sample"
    - "/api/kafka"



